#!/usr/bin/env ansible-playbook
---

- name: Check ansible version
  hosts: localhost
  vars: { min_ansible_version: 2.3.0 }
  tags: check-version
  tasks:
    - fail:
        msg: min ansible version is {{ min_ansible_version }}, ansible version is {{ ansible_version.string }}
      when: ansible_version.string | version_compare(min_ansible_version, 'lt')
      check_mode: False
      tags: always


- name: Clone a VM and basic renaming steps
  hosts: &hosts tst5
  gather_facts: False
  tags: clone

  vars_files:
    - vars/passwords.yml
    - vars/ext/legacy/oxa_vcenter.yml
    - vars/ext/legacy/oxa_networks.yml

  roles:
    
    - role: augeas
    - role: clone

      validate_certs: False
      password: '{{ vcenter_password }}'

      template_name: debian8.template13
      template_hostname: debian8

      vm_memory_mb: 1024
      vm_num_cpus: 1

      pysphere: localhost
      dhcpd: super1
      bastion: super1


- name: Rename first interface
  hosts: *hosts
  tags: rename-iface

  vars_files:
    - vars/ext/legacy/oxa_networks.yml

  roles:
    - role: if-rename-first
      admin_network: admin2
      admin_network_gw: 10.1.2.248


- name: Commit clone and rename changes
  hosts: *hosts
  tags: commit-clone
  tasks:
    - include: tasks/hg-com-etc.yml
      vars: { com: Clone and basic renaming steps }


- name: Commit DHCP changes
  hosts: super1
  tags: commit-dhcp
  tasks:
    - include: tasks/hg-com-etc.yml
      vars: { com: new node on admin2 via DHCP }


- name: Adds ifaces
  hosts: *hosts
  tags: ifaces

  vars_files:

    - vars/passwords.yml
    - vars/ext/ips.yml
    - vars/ext/legacy/oxa_vcenter.yml
    - vars/ext/legacy/oxa_networks.yml

  vars:
    pysphere: localhost

  roles:

    - { role: hg-etc-com, com: before applying ifadd role }
    - { role: vsphere-if-add, network: front2, default_gw_net: front2, validate_certs: False }
    - { role: hg-etc-com, com: after applying ifadd role }


- name: Allocate disks
  hosts: *hosts
  gather_facts: False
  tags: disks

  vars_files:

    - vars/passwords.yml
    - vars/ext/legacy/oxa_vcenter.yml
    - vars/ext/legacy/oxa_vm_default.yml

  vars:
    pysphere: localhost
    validate_certs: False
    diskpassword: '{{ luks_password }}'

  roles:

    - { role: hg-etc-com, com: before applying diskadd role }
    - { role: vsphere-disk-add, unit: 1, device: sdb, name: space, size: 10 }
    - { role: vsphere-disk-add, unit: 2, device: sdc, name: space2, size: 10 }
    - { role: hg-etc-com, com: after applying diskadd role }
