#!/usr/bin/env ansible-playbook
---

- name: Clone a VM and basic renaming steps
  hosts: &hosts tst5
  gather_facts: False
  tags: clone

  vars_files:
    - vars/passwords.yml
    - vars/ext/legacy/oxa_vcenter.yml
    - vars/ext/legacy/oxa_networks.yml

  roles:
    
    - role: augeas
    - role: clone

      validate_certs: False
      password: '{{ vcenter_password }}'

      template_name: debian8.template13
      template_hostname: debian8

      vm_memory_mb: 1024
      vm_num_cpus: 1

      pysphere: localhost
      dhcpd: super1
      bastion: super1

- name: Rename first interface
  hosts: *hosts
  tags: rename-iface

  vars_files:
    - vars/ext/legacy/oxa_networks.yml

  roles:
    - role: if-rename-first
      admin_network: admin2
      admin_network_gw: 10.1.2.248

- name: Allocate disks
  hosts: *hosts
  gather_facts: False
  tags: disks

- name: Show vaults
  hosts: localhost
  gather_facts: False
  tags: show

  vars_files: [ vars/passwords.yml ]

  tasks:

    - debug: { var: vcenter_password }
    - debug: { var: luks_password }
