---

# ansible-galaxy install -r requirements.yml

- src: git@github.com:thydel/ar-vsphere-clone.git
  scm: git
  name: clone
  version: tde

- src: git@github.com:thydel/ar-if-rename-first.git
  scm: git
  name: if-rename-first
  version: master

#- src: https://github.com/thydel/ar-if-rename-first.git
#  name: if-rename-first
#  version: master

- src: https://github.com/thydel/ar-vsphere-if-add.git
  name: vsphere-if-add
  version: master

- src: git@github.com:thydel/ar-vsphere-disk-add.git
  scm: git
  name: vsphere-disk-add
  version: master

- src: https://github.com/thydel/ar-hg-etc-com.git
  scm: git
  name: hg-etc-com
  version: use-module
